version: '3'
services:
  webtop:
    image: linuxserver/webtop
    container_name: webtop
    ports:
      - 3000:3000
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /home/yass/projekt:/usr/share/nginx/html
      - /home/yass/projekt/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped





